apiVersion: v1
kind: Service
metadata:
  name: {{name}}
  labels:
    app: pulsar
    component: broker
spec:
  ports:
    - port: 8080
      name: http
    - port: 6650
      name: pulsar
  clusterIP: None
  selector:
    app: pulsar
    component: broker
    cluster: {{name}}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{name}}
  labels:
    app: pulsar
    component: broker
    cluster: {{name}}
spec:
  containers:
    - name: broker
      image: apachepulsar/pulsar-all:latest
      command: ["sh", "-c"]
      args:
        - >
          bin/apply-config-from-env.py conf/standalone.conf &&
          bin/gen-yml-from-env.py conf/functions_worker.yml &&
          bin/pulsar standalone
      ports:
        - containerPort: 8080
        - containerPort: 6650
      envFrom:
        - configMapRef:
            name: broker-config
      env:
        - name: advertisedAddress
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: clusterName
          value: {{name}}
        - name: PF_pulsarFunctionsCluster
          value: {{name}}
      volumeMounts:
        - mountPath: /pulsar/data
          name: data-volume
  volumes:
    - name: data-volume
      emptyDir: {}
